
import { useState } from "react";
import api from "../services/api";
import ReactMarkdown from "react-markdown";
function AI() {
    const [resume, setResume] = useState(null);
    const [analysis, setAnalysis] = useState("");
    const [company, setCompany] = useState("");
const [role, setRole] = useState("");
const [coverLetter, setCoverLetter] = useState("");
const [interviewCompany, setInterviewCompany] = useState("");
const [interviewRole, setInterviewRole] = useState("");
const [questions, setQuestions] = useState("");
const [loading, setLoading] = useState(false);
   const handleAnalyze = async () => {
    if (!resume) {
        alert("Please upload a resume first.");
        return;
    }
 setLoading(true);
    try {
        const formData = new FormData();

        formData.append("resume", resume);

        const response = await api.post(
            "/ai/analyze-resume",
            formData,
            {
                headers: {
                    "Content-Type": "multipart/form-data",
                },
            }
        );

        setAnalysis(response.data.analysis);

    } catch (error) {
    console.error(error);

    alert(error.response?.data?.message || "Something went wrong");
}finally {
 setLoading(false);}
};
const handleGenerateCoverLetter = async () => {
    try {

        const response = await api.post("/ai/generate-cover-letter", {
            company,
            role,
        });

       setCoverLetter(response.data.coverLetter);

    } catch (error) {
        console.error(error);
    }
};
const handleGenerateQuestions = async () => {

    try {

        const response = await api.post(
            "/ai/generate-interview-questions",
            {
                company: interviewCompany,
                role: interviewRole,
            }
        );

       setQuestions(response.data.questions);

    } catch (error) {

        console.error(error);

    }

};
    return (
        <div className="min-h-screen bg-slate-100 p-8">

            <div className="max-w-6xl mx-auto">

                <h1 className="text-4xl font-bold text-slate-800">
                    🤖 AI Career Assistant
                </h1>

                <p className="text-gray-600 mt-2 mb-8">
                    Use AI to improve your resume, prepare for interviews and create personalized cover letters.
                </p>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

                    {/* Resume Analyzer */}

                    <div className="bg-white rounded-2xl shadow-lg p-6">

                        <div className="text-5xl mb-4">📄</div>

                        <h2 className="text-2xl font-bold">
                            Resume Analyzer
                        </h2>

                        <p className="text-gray-500 mt-3">
                            Upload your resume and receive AI-powered feedback.
                        </p>
                        <input
    type="file"
    accept=".pdf"
    onChange={(e) => setResume(e.target.files[0])}
    className="mt-6 block w-full border rounded-lg p-2"
/>
{resume && (
    <p className="mt-3 text-sm text-green-600">
        Selected: {resume.name}
    </p>
)}
{analysis && (
    <div className="mt-8 bg-white rounded-3xl shadow-xl border border-slate-200 overflow-hidden">

        {/* Header */}
        <div className="flex justify-between items-center px-6 py-4 bg-slate-50 border-b">

            <div>
                <h2 className="text-2xl font-bold text-slate-800">
                    📄 Resume Analysis
                </h2>

                <p className="text-sm text-slate-500">
                    Generated by Gemini AI
                </p>
            </div>

        </div>

        {/* Content */}

        <div className="p-6">

            <ReactMarkdown
                components={{

                    h1: ({children}) => (
                        <h1 className="text-3xl font-bold text-slate-800 mb-6">
                            {children}
                        </h1>
                    ),

                    h2: ({children}) => (
                        <h2 className="text-xl font-semibold text-blue-600 mt-8 mb-3">
                            {children}
                        </h2>
                    ),

                    p: ({children}) => (
                        <p className="text-gray-700 leading-7 mb-3">
                            {children}
                        </p>
                    ),

                    ul: ({children}) => (
                        <ul className="list-disc pl-6 space-y-2 mb-5">
                            {children}
                        </ul>
                    ),

                    li: ({children}) => (
                        <li className="text-gray-700">
                            {children}
                        </li>
                    ),

                    strong: ({children}) => (
                        <strong className="font-bold text-slate-900">
                            {children}
                        </strong>
                    )

                }}
            >
                {analysis}
            </ReactMarkdown>

        </div>

    </div>
)}

                       <button
                       onClick={handleAnalyze}
    disabled={loading}
    className={`w-full py-3 rounded-xl ${
        loading
            ? "bg-gray-400 cursor-not-allowed"
            : "bg-blue-600 hover:bg-blue-700"
    } text-white`}
>
    {loading ? "Analyzing..." : "Analyze Resume"}
</button>

                    </div>

                   {/* Cover Letter */}

<div className="bg-white rounded-2xl shadow-lg p-6">

    <div className="text-5xl mb-4">✍️</div>

    <h2 className="text-2xl font-bold">
        Cover Letter Generator
    </h2>

    <p className="text-gray-500 mt-3">
        Generate personalized cover letters in seconds.
    </p>

    <input
        type="text"
        placeholder="Company Name"
        value={company}
        onChange={(e) => setCompany(e.target.value)}
        className="w-full border rounded-lg p-3 mt-5"
    />

    <input
        type="text"
        placeholder="Job Role"
        value={role}
        onChange={(e) => setRole(e.target.value)}
        className="w-full border rounded-lg p-3 mt-3"
    />
    {coverLetter && (
    <div className="mt-6 bg-gray-50 rounded-xl p-5 whitespace-pre-wrap">

        <h3 className="text-xl font-bold mb-3">
            Generated Cover Letter
        </h3>
        <div className="mt-6 bg-white rounded-2xl shadow-lg p-6 border">
<ReactMarkdown>
    {coverLetter}
</ReactMarkdown>
        </div>

    </div>
)}

    <button
    onClick={handleGenerateCoverLetter}
    className="mt-6 w-full bg-green-600 hover:bg-green-700 text-white py-3 rounded-xl"
>
    Generate
</button>

</div>

                    {/* Interview */}

                    <div className="bg-white rounded-2xl shadow-lg p-6">

                        <div className="text-5xl mb-4">🎤</div>

                        <h2 className="text-2xl font-bold">
                            Interview Preparation
                        </h2>

                        <p className="text-gray-500 mt-3">
                            Practice AI-generated interview questions.
                        </p>

                        
                        <input
    type="text"
    placeholder="Company Name"
    value={interviewCompany}
    onChange={(e) => setInterviewCompany(e.target.value)}
    className="w-full border rounded-lg p-3 mt-5"
/>

<input
    type="text"
    placeholder="Job Role"
    value={interviewRole}
    onChange={(e) => setInterviewRole(e.target.value)}
    className="w-full border rounded-lg p-3 mt-3"
/>

<button
    onClick={handleGenerateQuestions}
    className="mt-6 w-full bg-purple-600 hover:bg-purple-700 text-white py-3 rounded-xl"
>
    Generate Questions
</button>
{questions && (
    <div className="mt-6 bg-gray-50 rounded-xl p-5 whitespace-pre-wrap">
        <h3 className="text-xl font-bold mb-3">
            Interview Preparation
        </h3>

        <ReactMarkdown>
            {questions}
        </ReactMarkdown>
    </div>
)}
                    </div>

                </div>

            </div>

        </div>
    );
}

export default AI;